### PR TITLE
Fix repo address in clone command

### PR DESCRIPTION
**Pull request by paw-lu**
Correct the repository address in the installation command from the README.

### CODE REVIEW

**Comment by joshfriend** [comment]
There's nothing incorrect about that URL, can you explain why you think it's wrong?

**Comment by paw-lu** [comment]
```zsh
❯ git --version
git version 2.25.0

❯ git clone git://github.com/pyenv/pyenv-update.git
Cloning into 'pyenv-update'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Operation timed out

❯ git clone https://github.com/pyenv/pyenv-update.git
Cloning into 'pyenv-update'...
remote: Enumerating objects: 56, done.
remote: Total 56 (delta 0), reused 0 (delta 0), pack-reused 56
Unpacking objects: 100% (56/56), 9.46 KiB | 88.00 KiB/s, done.
```

The `git`-prefixed address was not working for me, had to replace it with `https`.

**Comment by joshfriend** [comment]
the `git://` address worked fine for me, i would suspect your network or ISP is blocking the ssh port.

anyways, maybe `https://` is more reliable for most people

**Comment by paw-lu** [comment]
Yeah, I suspect it's a corporate network thing. Thanks!

**Pull request merged**
